# 触发workflow的条件
name: Node.js CI

on:
  push:
    # 只有master分支发生push事件时，才会触发workflow
    branches: [ master ]
  pull_request:
    branches: [ master ]

# jobs表示执行的一项或多项任务
jobs:
 # 任务的job_id，具体名称自定义，这里build代表打包
  build:
    # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - uses: actions/setup-node@v1
          with:
                node-version: v23.2.0 # 选择node版本
                
        # 装依赖
        - name: Install
          run: npm install
        # 装pkg
        - name: InstallENV
          run:  npm install -g rimraf pkg
        # 清除缓存
        - name: ClearTemp
          run:  rimraf dist  
        # 打包
        - name: Build
          run: pkg ./ --debug=true
